# Generated by Django 2.1.2 on 2018-10-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Title')),
                ('link', models.URLField(max_length=1000, unique=True, verbose_name='Link')),
                ('created', models.DateTimeField(verbose_name='Created at')),
                ('trend', models.CharField(max_length=1000, unique=True, verbose_name='Trend')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'db_table': 'article',
            },
        ),
    ]
