# Generated by Django 2.1.2 on 2018-10-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_agregator', '0003_auto_20181016_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.URLField(max_length=1000, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
